##################################################################################################################################################################
#1731. The Number of Employees Which Report to Each Employee
#Write a solution to report the ids and the names of all managers, the number of employees who report directly to them, and the average age of the reports rounded to the nearest integer.


-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
